apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
  labels:
    app: capstone-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      containers:
      - name: capstone-app
        image: subrockmann/udacity_capstone:v1
        ports:
        - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: capstone-lb
  labels:
    app: capstone-app
spec:
  type: LoadBalancer
  selector:
    app: capstone-app
  ports:
    - port: 80
      targetPort: 80